### PR TITLE
New assembler args

### PR DESCRIPTION
**Pull request by nicklausw**
This is not ready to be merged; just to show progress. The assembler can now do *nix style arg input, but no makefiles in the repo have been modified to conform and the linker is still in its same style (maybe keep it that way?). Also I need Ville to check and make sure that the code conforms to WLA's general style and is safe.

So far, I've changed this:
```wla-6502 -vo -Ibla -DBLA main.s main.o```
to the much cleaner:
```wla-6502 -v -I bla -D BLA -o main.o main.s```

Everything seems to work so far.

### CODE REVIEW

**Comment by nicklausw** [comment]
Okay, defines are now properly back. Spacing is more strict than before.

This:
```-DBLARG=$100```
is now:
```-D BLARG = $100```

**Comment by nicklausw** [comment]
Question! Should I also implement the new args for wlalink? The structure with the linkfile and output going last is the same (might add -o eventually), just the options are flag-style. Why? Because I might want to add an option to put object files in through the command line, and that plus the library directory option would make things ugly.

**Comment by nicklausw** [comment]
Just brought back the assembler's ability to automatically come up with output names.

This:
`wla-z80 pong.s`
generates a file named 'pong.o'.

**Comment by vhelin** [comment]
Cool! :)

On 23 May 2016 21:38, "nicklausw" <notifications@github.com> wrote:
>
> Just brought back the assembler's ability to automatically come up with
output names.

**Comment by nicklausw** [comment]
I think this pull request is just about ready for now. But, GitHub is glitching out; some of my commits aren't showing up, so uh...

Yeah, though, the assembler and linker now have new flag parsers implemented, are you willing to merge it all in or is there more that you'd like to see done first?

**Comment by nicklausw** [comment]
https://status.github.com/ github is being silly, it seems.

**Comment by vhelin** [comment]
On 23 May 2016 22:28, "nicklausw" <notifications@github.com> wrote:
>
> I think this pull request is just about ready for now. But, GitHub is
glitching out; some of my commits aren't showing up, so uh...
>
> Yeah, though, the assembler and linker now have new flag parsers
implemented, are you willing to merge it all in or is there more that you'd
like to see done first?

Almost bedtime here, have early wake up, so let's see tomorrow...

**Comment by nicklausw** [comment]
Defines are working again, no more crashes, simpler code. Now I'm glad you went to bed...

**Comment by nicklausw** [comment]
So is this going to be merged in? I need to know whether or not to prepare a post on NESDev explaining the flag changes.

**Comment by vhelin** [comment]
Ooops, sorry for the delay, again. Did some more scuba diving and changed
cities, my vacation is nearing its end, 10 more days to go... I got a huge
upgrade to the parser in WLA via email, and that should be really good, but
needs merging also. Now it's about to rain here, and I'm out to have lunch.
Later back here in the hotel, no other plans for today...

**Comment by vhelin** [comment]
Looks good, though I'm going to reformat the code so it looks like all the other code in the project - don't want to WLA DX degenerate into collection of numerous different coding styles. :)

**Comment by nicklausw** [comment]
Sounds good to me. Perhaps eventually we'll write up a stylistic guide?

Also, I wrote the NESDev post super fast but it looks alright. Don't even think I'll have time to go to SMSPower, where WLA is the assembler of choice...

**Comment by vhelin** [comment]
On Tue, May 31, 2016 at 6:35 PM, nicklausw <notifications@github.com> wrote:

> Sounds good to me. Perhaps eventually we'll write up a stylistic guide?
>

Well, just look at the other/old code... :) Anyway, it's just easier for
the eyes and the brain if the coding style stays as constant as possible
throughout the project. White space, curly brackets, function naming
style... Not much there.


> Also, I wrote the NESDev post super fast but it looks alright. Don't even
> think I'll have time to go to SMSPower, where WLA is the assembler of
> choice...
>

Cool! Let's hope the old users don't rage quit over the changes they now
need to do to their scripts / makefiles... :)

**Pull request merged**
