### PR TITLE
Fix sphinx CMake mistakes

### PR DESCRIPTION
**Pull request by Neui**
Continuation of #121, [my comment](https://github.com/vhelin/wla-dx/pull/121#issuecomment-317469693):

>Oops, I had the detection in place that it wouldn't build when sphinx was missing, I just used the wrong if-syntax..
>
>For the second error, I've reordered the arguments so that all options are the first before the files, although I don't know why it works for me (also using cygwin, sphinx-build  1.6.3).
>
> I've also found an error when having an in-source-build (like you do) that cleaning would delete the doc/man folder. I now took an another name for the building (`gen-man`). I've only tested this in an out-of-source build (this is what CMake recommends), and building in an n-source-build worked, so I never checked clean.
>
>Also, you've already merged this. Can you "remerge" or do I have to open an another pull request?

Also, by the way, you don't need an seperate `Neui-doc-sphinx`  branch, you can just add my repository as a remote (`git remote add neui https://github.com/Neui/wla-dx`), fetch (`git fetch`) and then check it out (aka go to the commit of the branch, `git checkout neui/doc-sphinx`). (Or just do [something like this](https://help.github.com/articles/checking-out-pull-requests-locally/))

### CODE REVIEW

**Comment by vhelin** [comment]
Thanks, now make doesn't fail any more... But I can't seem to find the generated documents anywhere. Under which folder they should be? Make's output doesn't mention the documents any more, the last item on the list is wlalink... ?

**Comment by Neui** [comment]
Have you checked `binaries/doc`?

**Comment by vhelin** [comment]
I don't have that directory doc under binaries... ? Just the executables.

$ li binaries/
total 2577
drwxrwx---+ 1 ville ville      0 Jul 24 19:25 ./
drwxrwx---+ 1 ville ville      0 Jul 24 19:25 ../
-rwxrwx---+ 1 ville ville    119 Jul 10  2015 .gitignore*
-rwxrwxr-x+ 1 ville ville 279883 Jul 24 19:25 wla-6502.exe*
-rwxrwxr-x+ 1 ville ville 284491 Jul 24 19:25 wla-6510.exe*
-rwxrwxr-x+ 1 ville ville 316050 Jul 24 19:25 wla-65816.exe*
-rwxrwxr-x+ 1 ville ville 284491 Jul 24 19:25 wla-65c02.exe*
-rwxrwxr-x+ 1 ville ville  68991 Jul 24 19:25 wlab.exe*
-rwxrwxr-x+ 1 ville ville 297451 Jul 24 19:25 wla-gb.exe*
-rwxrwxr-x+ 1 ville ville 289611 Jul 24 19:25 wla-huc6280.exe*
-rwxrwxr-x+ 1 ville ville 173755 Jul 24 19:25 wlalink.exe*
-rwxrwxr-x+ 1 ville ville 283760 Jul 24 19:25 wla-spc700.exe*
-rwxrwxr-x+ 1 ville ville 321246 Jul 24 19:25 wla-z80.exe*

**Comment by Neui** [comment]
Weird, it creates one for me and it works. What CMake version do you use? I've only tested on CMake 3.3.2 and 3.5.1. Maybe an older version just doesn't create the folder if missing?

```
Scanning dependencies of target doc-man
[ 98%] Generating man pages
[ 98%] Built target doc-man
Scanning dependencies of target doc-shtml
[ 99%] Generating single HTML page documentation
WARNING: html_static_path entry u'/tmp/wla/doc/_static' does not exist
[ 99%] Built target doc-shtml
Scanning dependencies of target doc-stext
[100%] Generating simple text documentation
[100%] Built target doc-stext
Scanning dependencies of target doc
[100%] Built target doc

Neui@NeuIi /tmp/wla (master)
$ tree binaries/
binaries/
├── doc
│   ├── wla-6502.1
│   ├── wla-6510.1
│   ├── wla-65816.1
│   ├── wla-65c02.1
│   ├── wlab.1
│   ├── wlad.1
│   ├── wla-dx.7
│   ├── wla-dx.html
│   ├── wla-dx.txt
│   ├── wla-gb.1
│   ├── wla-huc6280.1
│   ├── wlalink.1
│   ├── wla-spc700.1
│   └── wla-z80.1
├── wla-6502.exe
├── wla-6510.exe
├── wla-65816.exe
├── wla-65c02.exe
├── wlab.exe
├── wla-gb.exe
├── wla-huc6280.exe
├── wlalink.exe
├── wla-spc700.exe
└── wla-z80.exe

1 directory, 24 files
```

Also, your E-Mail response includes an github link to mute this, you probably don't want to share that link. ;)

**Comment by vhelin** [comment]
On Mon, Jul 24, 2017 at 7:44 PM, Neui <notifications@github.com> wrote:

> Weird, it creates one for me and it works. What CMake version do you use?
> I've only tested on CMake 3.3.2 and 3.5.1. Maybe an older version just
> doesn't create the folder if missing?
>

I have CMake 3.6.2 here, the latest from Cygwin servers...


> Scanning dependencies of target doc-man
> [ 98%] Generating man pages
> [ 98%] Built target doc-man
> Scanning dependencies of target doc-shtml
> [ 99%] Generating single HTML page documentation
> WARNING: html_static_path entry u'/tmp/wla/doc/_static' does not exist
> [ 99%] Built target doc-shtml
> Scanning dependencies of target doc-stext
> [100%] Generating simple text documentation
> [100%] Built target doc-stext
> Scanning dependencies of target doc
> [100%] Built target doc
>
>
I don't get any of these in make's output here, the 100% item is wlalink...


>
>
> Neui@NeuIi /tmp/wla (master)
> $ tree binaries/
> binaries/
> ├── doc
> │   ├── wla-6502.1
> │   ├── wla-6510.1
> │   ├── wla-65816.1
> │   ├── wla-65c02.1
> │   ├── wlab.1
> │   ├── wlad.1
> │   ├── wla-dx.7
> │   ├── wla-dx.html
> │   ├── wla-dx.txt
> │   ├── wla-gb.1
> │   ├── wla-huc6280.1
> │   ├── wlalink.1
> │   ├── wla-spc700.1
> │   └── wla-z80.1
> ├── wla-6502.exe
> ├── wla-6510.exe
> ├── wla-65816.exe
> ├── wla-65c02.exe
> ├── wlab.exe
> ├── wla-gb.exe
> ├── wla-huc6280.exe
> ├── wlalink.exe
> ├── wla-spc700.exe
> └── wla-z80.exe
>
> 1 directory, 24 files
>
>
Weird, it looks like here make skips the whole documentation part...


>  Also, your E-Mail response includes an github link to mute this, you
> probably don't want to share that link. ;)
>

Same here, don't click it. :)

**Comment by Neui** [comment]
What does `make doc` say? Try doing `cmake .` first to regenerate your Makefiles (although it should do it automatically)... Does it work on a clean state? (Try clone it to an different directory and test it there)

Also, should we chat over IRC? This is getting a bit too "chatty". What about channel `#wla-dx` at freenode? (Unsure if it is used)

**Comment by vhelin** [comment]
"make doc" says nothings. But after I downloaded the project from GitHub to a new dir and tried making there, I got this error:

...

[ 98%] Linking C executable ../binaries/wlalink.exe
[ 98%] Built target wlalink
[ 99%] Generating simple text documentation

Extension error:
Could not import extension singletext (exception: cannot import name logging)
make[2]: *** [doc/CMakeFiles/doc-stext.dir/build.make:83: binaries/doc/wla-dx.txt] Error 1
make[1]: *** [CMakeFiles/Makefile2:1238: doc/CMakeFiles/doc-stext.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

...

I need an extension called "singletext"? Where can I get it from, any ideas?

I'm now at #wla-dx, at freenode, can see you there. :)

**Pull request merged**
