### PR TITLE
no-library-file macros

### PR DESCRIPTION
**Pull request by nicklausw**
The same code but not as repetitive with making sure libraries aren't getting things they shouldn't.

### CODE REVIEW

**Comment by cr1901** [comment]
This is a good idea. A few style changes: please wrap your macro in a do{}while(0): http://c-faq.com/cpp/multistmt.html, and make sure all directives are qualified with a period in your macro invocation when it matches the old code (your "SLOT" macro invocation is missing the leading period).

**Comment by nicklausw** [comment]
So wait, does a do while statement always loop at least once? I assume so since 0 never equals a non-zero value.

**Comment by nicklausw** [comment]
It works apparently so here you go.

**Comment by vhelin** [comment]
Nice, thanks! :)

**Comment by nicklausw** [comment]
Now I'll just have to think of a bunch of other ways to TRULY shrink pass_1.c's mass...it's not really good that one file in the project is 7000 lines long, but most of it is one function so it can't be helped.

**Comment by vhelin** [comment]
If someone wants to start refactoring, pass_1.c and that one huge function
is a great place to start from. :) But before doing anything major there,
I'd like to see the new branch parserUpgrade assemble and link everybody's
projects first, and after it gets merged to master, then it'd be a good
time to do something else biggish as otherwise we have too many changes in
the repo and too little testing plus all the conflicts... :)

**Comment by cr1901** [comment]
>>So wait, does a do while statement always loop at least once? I assume so since 0 never equals a non-zero value.

Yes. do{}while(0) is a C idiom to prevent multi-line macros from causing errors when used in certain contexts, such as if-else.

**Pull request merged**
