### PR TITLE
Extract Mersenne Twister to it's own file

### PR DESCRIPTION
**Pull request by lhsazevedo**
As suggested in https://github.com/vhelin/wla-dx/pull/361#issuecomment-765751523

### CODE REVIEW

**Comment by vhelin** [comment]
Nice, thanks!

**Comment by vhelin** [comment]
I can confirm that AmigaOS3 (smake) building works!

**Comment by lhsazevedo** [comment]
Great :rocket: 
One day I'll try AmigaOS3 on FS-UAE, never done this, only seen Amiga on demo compos.

**Comment by vhelin** [comment]
One problem I have with Amiga is that I fail to redirect the "amiga" script's output to a file, it just keeps on going to console...

execute amiga > output.txt
execute amiga 2> output.txt
execute amiga *> output.txt

... all fail...

It'd be nice to collect the output to a file for easy browsing. Setting the WinUAE emulator speed to very low, waiting for something interesting to happen, and then breaking the script execution with CTRL-C is a really painful way to dig into what happens on the Amiga side...

**Pull request merged**
