### PR TITLE
Child Labels

### PR DESCRIPTION
**Pull request by Drenn1**
This is the next step in my quest to hide all the labels from myself...

Implements #33. From the readme:

```
Labels starting with "@" are considered to be child labels. They can only be
referenced within the scope of their parent labels, unless the full name is
specified. When there is more than one "@", the label is considered to be
a child of a child.

Here are some examples of child labels:

PARENT1:
@CHILD:
@@SUBCHILD

PARENT2:
@CHILD:

This is legal, since each of the @CHILD labels has a different parent. You can
specify a parent to be explicit, like so:

        jr PARENT1@CHILD@SUBCHILD
```

It can go 10 levels deep, although you're likely to hit the name length limit by that point. It might be worth bumping that up.

### CODE REVIEW

**Comment by cr1901** [comment]
I REALLY am doing a poor job as a maintainer, and I sincerely apologize. Let's wait until Ville submits his new bug fixes he received via email and I'll see about merging this.

**Comment by Drenn1** [comment]
Just for the record, this doesn't conflict with the "parserUpgrade" branch. There is one merge conflict, but it's just whitespace.

So, you can merge this any time now... =P

**Comment by vhelin** [comment]
Oh man, GitHub doesn't let me merge the pull request, because of that one conflict. Can you Mr. Jones merge this one? :)

**Comment by Drenn1** [comment]
This is actually a different conflict caused by the name-length fix you just merged. Fixed :)

I also recommend, again, increasing MAX_NAME_LENGTH now that you can, since I very frequently ran into that limit, due to the way child labels stack their names together with their parents.

**Comment by vhelin** [comment]
Thank you! Sure, let's increase that MAX_NAME_LENGHT, give me a sec... :)

**Comment by vhelin** [comment]
Thanks!

Just increased MAX_NAME_LENGTH -> 255 - I hope it works all across the
code. :)

Anyway, it seems that at least my CMake here is defaulting to making builds
with WLA_DEBUG and WLALINK_DEBUG defined - are my local sources just
somehow weird or are you seeing this behaviour as well?

I've been coding C# for the past 6+ months so I might be forgetting
something here, but building WLA DX with

  cmake -G "Unix Makefiles"

gives me DEBUG executables... ???

**Comment by Drenn1** [comment]
I'm not getting that behaviour... that's really weird. Did it only started happening after merging this branch? :/

**Comment by cr1901** [comment]
`-DCMAKE_BUILD_TYPE=Debug` on the command-line for Debug binaries, which I think should be the default?

**Pull request merged**
