### PR TITLE
Hashmaps and namespaces

### PR DESCRIPTION
**Pull request by Drenn1**
Okay here it is. I did my best to make sure the examples are working, but there are a lot of features and I don't understand them all (BANKHEADERs?). The examples that use them do assemble though, so I guess that's a good sign. In theory the only behaviour that should have changed is how labels are located, although that's kind of important.

This contains the commits from #82, I had to change them a fair bit though.

I made some modifications to the hashmap, it should work even if everything is a collision. I have some tests in my "hash-test" branch.

This reduces my project's assembly time from ~11s to ~2s on my computer, and 2.5 minutes to 15 seconds on my laptop! It was hellish working on that thing. =P

### CODE REVIEW

**Comment by vhelin** [comment]
Wow, now that's a big one. :) It's 01:46am here, I've spent this evening
hunting bugs in WLA DX, and my eyes are closing themselves, so I'll try to
go through your work tomorrow, and do some tests of my own. Thanks! :)

BTW: Just curious, what CPU your laptop has (and what a speedup!)?

**Comment by Drenn1** [comment]
It's an AMD E-350 processor, 1.6GHz. Which it can't even maintain due to overheating. I didn't really mind it that much until I learned what true speed was with my desktop.

**Comment by vhelin** [comment]
Urgh, my recent bugfixes conflict with this branch, and it's again 00:39am here - took a long time to do that latest bugfix...

I've checked this one out only partially, and will go through the rest of the code tomorrow, but looks quite good. The only thing that needs updating is the file format; as you've modified the WLA's object file format, we'll need to drop supporting "WLAL" and "WLAW" formats, and change the headers to "WLAM" and "WLAX". But I can do all this plus other small mods as necessary... :) More tomorrow.

**Comment by vhelin** [comment]
Ok guys, I read through the code mods, merged this branch to master, and manually resolved the conflicts. I hope I didn't break anything as this was my first such operation using Git. :) With SVN this would have been simpler, a little...

Anyway, looked good, didn't test it much, though, but will add more tests for it if not today then tomorrow.

Thanks Drenn1! :+1:

**Comment by Drenn1** [comment]
Awesome. :) I'm kinda surprised you had trouble merging though, I feel like git could've handled most of the differences. Not that I've ever had to do such a large merge. :P

**Comment by nicklausw** [comment]
Niiiiiiiice, efficiency is always good. *thumbs up*

Did you look into what crxxxx (too lazy to remember his username) said about the code not being ANSI C though?

**Comment by vhelin** [comment]
Well while you were creating this feature upgrade I made some bug fixes,
and we ended up editing two same functions, but merging them manually
wasn't a big deal. :)

**Comment by Drenn1** [comment]
@niclausw cr was just cautioning me I think. Anyway it looks like "-pedantic -ansi" are already in the compile flags so it ought to be compliant.

**Comment by nicklausw** [comment]
Sweet then. I'll have to do some speed comparisons with one of my old projects to see how nice hashmaps work.

**Pull request merged**
