### PR TITLE
More documentation sphinx fixes (1.2.3 support)

### PR DESCRIPTION
**Pull request by Neui**
Continuation of #153. Cygwin still ships sphinx 1.2.3 in their repositories. This PR tries to make it work on that (and newer) version. Please test this PR before merging! I don't think you really want so many "useless" PRs when it can be done just in one. ;)

(See this [comment's last paragraph](https://github.com/vhelin/wla-dx/pull/153#issue-245133018), be sure to run `cmake .` before so you get the newest Makefiles)

### CODE REVIEW

**Comment by vhelin** [comment]
Yeah, this works! 👍 Thank you!

**Comment by cr1901** [comment]
I was unable to install docs using Sphinx 1.51b, just fyi.

* [This line](https://github.com/vhelin/wla-dx/blob/master/doc/sphinx/singletext.py#L14) returns `AttributeError` instead of `ImportError`.
* [Lines 67-68](https://github.com/vhelin/wla-dx/blob/master/doc/sphinx/singletext.py#L67-L68) error out with `TypeError: inline_all_toctrees() missing 1 required positional argument: 'traversed'`
* Jinja claims that `metatags` does not exist.

Upgrading to Sphinx 1.63 (using the `pip1 provided with `mingw-w64-i686-python3`) solves the problem, but I was a bit surprised that a version in between did not work. Just wanted to document :).

**Comment by Neui** [comment]
I've looked at it and fixed the first 2 problems, I hope. (Just tested all version that were available on pip; 1.4a1 and 1.4.7 "sticks out" as not working, but their error messages indicate more of an internal problem)

I'm going to push the new changes in an separate branch (that makes other things better). However, did the last error (`metatags` not being found) cause an error or just a warning? If it is just a warning, then it probably can just be ignored, otherwise I'd have to check what combination of versions of packages you need to reproduce it test it with an another change..

**Comment by cr1901** [comment]
Here were the old packages that were uninstalled, if it helps:

```
  Found existing installation: docutils 0.12
    Uninstalling docutils-0.12:
      Successfully uninstalled docutils-0.12
  Found existing installation: pytz 2015.6
    Uninstalling pytz-2015.6:
      Successfully uninstalled pytz-2015.6
  Found existing installation: babel 2.3.4
    Uninstalling babel-2.3.4:
      Successfully uninstalled babel-2.3.4
  Found existing installation: MarkupSafe 0.23
    Uninstalling MarkupSafe-0.23:
      Successfully uninstalled MarkupSafe-0.23
  Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
  Found existing installation: Jinja2 2.8
    Uninstalling Jinja2-2.8:
      Successfully uninstalled Jinja2-2.8
  Found existing installation: requests 2.9.1
    Uninstalling requests-2.9.1:
      Successfully uninstalled requests-2.9.1
  Found existing installation: alabaster 0.7.9
    Uninstalling alabaster-0.7.9:
      Successfully uninstalled alabaster-0.7.9
  Found existing installation: setuptools 18.5
    Uninstalling setuptools-18.5:
      Successfully uninstalled setuptools-18.5
  Found existing installation: colorama 0.3.7
    Uninstalling colorama-0.3.7:
      Successfully uninstalled colorama-0.3.7
  Found existing installation: sphinx 1.5b1
    Uninstalling sphinx-1.5b1:
```

**Comment by Neui** [comment]
I created a new python environment (virtualenv) and installed your packages. I couldn't reproduce issue 3 (Jinja), but let's hope it is rare. The fix for the first 2 issues are already fixed in a [commit](https://github.com/Neui/wla-dx/commit/f168da2981d358a03cabf71655327bfec136f8c9), but they're not pushed yet. It is going to be in a branch with other stuff (mainly CMake things, but also some cleanness and userfriendly-ness), and that might take a while till I make a PR for it.

If you want to test the sphinx-change, just checkout commit `f168da` on my repo and do your testing. ;)

**Comment by GPHemsley** [comment]
I can confirm that f168da fixes the build process for sphinx 1.4.9 and/or 1.5.3.

**Pull request merged**
