### PR TITLE
Port documentation to Sphnix

### PR DESCRIPTION
**Pull request by Neui**
There is already an documentation - the `README`. However, it is only text. This is fine for the most part, however the narrow can make it annoying if you have just so more space.

[Sphnix](http://www.sphinx-doc.org/) allows us to write documentation and allows to be exported in: colorful HTML, manpages and even a simple text-file. The main thing i wanted to go was manpages, but HTML is easier first.

This is still almost done, but still **WIP**:
- [X] Basic CMakeLists
  - [X] Add support manpages
- [x] Port documentation
  - [x] Write manpages (they need special care)
- [x] Little things (see below)

### CODE REVIEW

**Comment by vhelin** [comment]
I have to admit that I have no idea about Sphinx. :) Manpages and HTML I know, so I guess this is all good. :+1: Though is it better to wait a bit before merging this to base/master?

**Comment by Neui** [comment]
I have no idea about Sphnix too ;). But i kinda figured it out and currently porting the existing documentation (the one in the `README`) to this thing.

You can try it out by pulling it and making it. `make doc` will do it and put the files into `binaries/doc` and then view `wla-dx-doc.html` (I might change it to `wla-dx.html`) with a web browser or `wla-dx.1` with `man`.

The only thing i am unsure is what manpage-category i should put `wla-dx` to. Currently it is 1, but it is for applications (like `wlalink`). Do you have an idea?

**Comment by vhelin** [comment]
About the manpage-category number, I found this in the Internets:

...
The table below shows the section numbers of the manual followed by the 
types of pages they contain.

   1   Executable programs or shell commands
   2   System calls (functions provided by the kernel)
   3   Library calls (functions within program libraries)
   4   Special files (usually found in /dev)
   5   File formats and conventions eg /etc/passwd
   6   Games
   7   Miscellaneous  (including  macro  packages and conven‐
       tions), e.g. man(7), groff(7)
   8   System administration commands (usually only for root)
   9   Kernel routines [Non standard]
...

1 or 7, I'd say. I guess 1 is better. Do you know in which category other assemblers are?

**Comment by Neui** [comment]
ld (linker), gcc (compiler), nasm (assembler) and as (GNU assembler</sub>, supports Z80</sub>) uses category 1 (because they're applications)..

I looked at groff(7) and groff(1). The former has `a short reference for the GNU roff language` where as the latter `front-end for the groff document formatting system`. So category 7 is used for like "manuals".

So i suggest:

* `wla-dx` goes to category 7 (`wla-dx.7`)
* `wlalink` goes to category 1 (`wlalink.1`)
* `wla-CPU` goes to category 1 (`wla-CPU.1`) (note that the CPU is replaced with eg. `gb`)

**Comment by vhelin** [comment]
Sounds good! :)

**Comment by Neui** [comment]
The basic thing is completed! But there are small things I'd like to do:

- When #123 is fixed (nice number by the way), I'll try to port it to this
- Rename `wla-dx-doc.{html,txt}` to `wla-dx.{html,txt}`
- Inlcude manpages in wla-dx (non-manpage version, or else.. it would be weird)
- Custom HTML design/theme
    - I thought like the design in the old Internet (like http://www.villehelin.com/wla.html )
    - Current theme doesn't wrap text (fixed width, annoying)
    - single page HTML uses assets from external folder; Maybe eliminate that to get a "true" single page/file
- Add Table of Contents of the (single page) HTML

Also, sphnix (or one of the packages it uses) is buggy on Windows... On my Ubuntu laptop, i get numbered sections where in Windows i don't get these..

**Comment by luizperes** [comment]
BTW, I Love it!!!

**Comment by nicklausw** [comment]
I guess development on new documentation has been put on hold. Sucks, it was looking good.

**Comment by luizperes** [comment]
Hi @nicklausw, at least by the checklist, it is nearly done, isn't it?

**Comment by Neui** [comment]
I'm sorry, I lost interest. Currently I have holidays so I could pick it up again. It is pretty complete, indeed. Current status of things:

For the HTML theme, maybe I just use the current one and modify it a bit so it isn't that bloated (it includes JavaScript scripts that is apparently not really used) and more usable (fixed width, annoying on narrow browser window). Not so sure about the license of the theme.

The tables width is something small (and only in the second section "Assembler Directives"), but I'd like to fix it, because it bothers me. The man-version tables doesn't display them full-width, which is annoying because of wasted space. Not so sure what I can do.

Also, the `globalindex.py` must be updated because "`sphinx.util.compat.Directive` is deprecated".

Due to the includes-hack for the one-file-text-documentation, it spits out the warning `duplicate label codesub6502`. I'd like also to get rid of it.

**Comment by luizperes** [comment]
That sounds great @Neui! Thanks for that!

**Comment by Neui** [comment]
It is pretty complete that I can say it could be merged. Obviously needs sphinx (`pip install Sphinx`) and should build without it if it couldn't be found. I primary worked with the HTML version, but the text-version seems to be OK (with the exception of the absence of numbered sections)

Plans for the future:

* Get numbered sections for the text-version/builder
* Create a custom [sphinx domain](http://www.sphinx-doc.org/en/stable/domains.html) for the directives (for easier referencing)
* Glossary

**Comment by vhelin** [comment]
I have plenty of time tomorrow to test this, and if all works I'll merge.

**Comment by vhelin** [comment]
It seems that WLA DX cannot be built any more without sphinx-build as this is what I get:

...

$ cmake -G "Unix Makefiles"
-- Couldn't find sphinx-build
CMake Error at doc/CMakeLists.txt:31 (message):
  sphinx-build not found


-- Configuring incomplete, errors occurred!
See also "/cygdrive/v/wla-dx/CMakeFiles/CMakeOutput.log".
...

I think it's quite important that WLA DX builds without sphinx-build, so if anyone can make this possible, please and thank you. :)

**Comment by vhelin** [comment]
Also, any ideas how to get that sphinx-build for Cygwin?

**Comment by vhelin** [comment]
I merged this pull request with the master, and found that Sphinx for Cygwin - it was under Python... :)

Now my build crashes at the end to this:

...

[ 98%] Built target wlalink
Scanning dependencies of target doc-stext
[ 99%] Generating simple text documentation
Error: Cannot find file '-d'.
Error: Cannot find file '/cygdrive/v/wla-dx/doc/stext.doctree'.
make[2]: *** [doc/CMakeFiles/doc-stext.dir/build.make:83: binaries/doc/wla-dx.txt] Error 1
make[1]: *** [CMakeFiles/Makefile2:1238: doc/CMakeFiles/doc-stext.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

...

Any ideas?

**Comment by Neui** [comment]
Oops, I had the detection in place that it wouldn't build when sphinx was missing, I just used the wrong if-syntax..

For the second error, I've reordered the arguments so that all options are the first before the files, although I don't know why it works for me (also using cygwin, sphinx-build  1.6.3).

I've also found an error when having an in-source-build (like you do) that cleaning would delete the doc/man folder. I now took an another name for the building (`gen-man`). I've only tested this in an out-of-source build (this is what CMake recommends), and building in an n-source-build worked, so I never checked clean.

Also, you've already merged this. Can you "remerge" or do I have to open an another pull request?

**Comment by vhelin** [comment]
On Mon, Jul 24, 2017 at 7:01 PM, Neui <notifications@github.com> wrote:

> Oops, I had the detection in place that it wouldn't build when sphinx was
> missing, I just used the wrong if-syntax..
>
> For the second error, I've reordered the arguments so that all options are
> the first before the files, although I don't know why it works for me (also
> using cygwin, sphinx-build 1.6.3).
>
> I've also found an error when having an in-source-build (like you do) that
> cleaning would delete the doc/man folder. I now took an another name for
> the building (gen-man). I've only tested this in an out-of-source build
> (this is what CMake recommends), and building in an n-source-build worked,
> so I never checked clean.
>
> Also, you've already merged this. Can you "remerge" or do I have to open
> an another pull request?
>

If you can do a new pull request, that'd be great! Thanks for the great
work. :)

**Pull request merged**
