### PR TITLE
Added Intel 8008 support

### PR DESCRIPTION
**Pull request by a0r10n**
- Uses old syntax 8008. 
- Uses $FF for HLT.
- Uses $07 for RET.
- Uses $44 for JMP.
- Uses $46 for CAL.
- Decimal numbers for ports and resets.

Why? Seemed like a good choice for learning how to extend WLA.

I apologize for anything unusual or untoward about this pull request; I'm new to these features.
I am open to feedback, and supporting this section if need be. (Though, the 8008 is really basic and doesn't use that much of WLA beyond that that everything else uses.)

### CODE REVIEW

**Comment by cr1901** [comment]
This is awesome, but there is a _huge_ amount of changed lines that seem to be whitespace-only changed. Could you fix that so that only the lines that you modified/added appear in the diff?

**Comment by a0r10n** [comment]
Acugh, stupid editor.
I'll see to it that whitespace is preserved.

**Comment by a0r10n** [comment]
Now it lines up much better.

I don't know how much demand there is for 8008 support; only system I can think of off the top of my head is the Altair 8800... but it seems somewhat common as a hardware hobbyist's CPU, and it's extremely simple to support.

**Comment by vhelin** [comment]
Wow, this is pretty cool! :) Thanks for the hard work, I'll try to check out this PR today or latest tomorrow.

I'm working myself on adding MC6809 support at the moment, so please anyone, don't create a pull request for support for MC6809, I want to finish it myself, LOL. :D

**Comment by vhelin** [comment]
Hmm, that was a small PR for a new CPU. 👍 Will need to edit the historical makefiles etc., but I can do that.

**Comment by a0r10n** [comment]
Oopsie, forgot the makefiles. I uploaded them to my fork, and also updated the documentation.
Sorry.

**Comment by vhelin** [comment]
I just made couple of other changes to amigaos4, CHANGELOG and then some
docs. Nothing critical, though...

**Pull request merged**
