### PR TITLE
spc700 1-bit opcode // Makefile incbin

### PR DESCRIPTION
**Pull request by bazzinotti**
This PR provides insight behind #319 (makefile) and #320 (spc700 1-bit opcode). It should not be viewed as a polished solution, but to get the ball rolling if you're interested in these adjustments I made to wla-dx.

### CODE REVIEW

**Comment by vhelin** [comment]
Couple of things that need fixing before this can be merged to master:

* f = fopen("/dev/zero", "rb"); - does this work on Windows or Amiga? I guess not... :P
  all code must work under Windows, Linux, Amiga, MSDOS...
  Take a look at main.c:generate_tmp_name() for a similar case
* All SPC700 specific code should be inside #if defined(SPC700) ... #endif

Did you run run_tests.sh for these, does it run without errors?

**Comment by bazzinotti** [comment]
Thanks for your quick reply. The tests run without errors. My last commit
made sure of it.

I'll get those 2 points done, retest and push.

**Comment by vhelin** [comment]
Any news on the progress? I'm just thinking about releasing v9.11 soon...

**Comment by bazzinotti** [comment]
I'm swamped right now 😅 I have a lot on my plate. I don't expect to get to
it soon.

**Comment by vhelin** [comment]
Hi!

We found a general solution that works on all platforms in pull request #383. But about the SPC 1-bit opcode part of your pull request - do you have the time to fix the conflicts / just submit that part, or would it be ok if I copied that part of your pull request and added the fix myself? I'll give you the credits in the commit message. :)

**Comment by bazzinotti** [comment]
Glad to see this reached the finish line! Cheers, Ville and friends

**Pull request closed without merging**
