### PR TITLE
Change definitions to use heap-allocated strings

### PR DESCRIPTION
**Pull request by maxim-zhao**
Part of #472

### CODE REVIEW

**Comment by maxim-zhao** [comment]
Hmm, Valgrind says it is leaking, I'll have a look later...

**Comment by maxim-zhao** [comment]
I think this is ready to merge now...

**Comment by vhelin** [comment]
Thanks!

**Comment by maxim-zhao** [comment]
Thanks for eb67746e7511d91dc9616aecb12ecad828e7473e - I had tried to do that myself but I wasn't sure about the part where it seemed to be copying substrings.

**Comment by vhelin** [comment]
In the code that I modded there really should not be any substrings, I was just circulating that strlen(s->string) in a variable to avoid recalculating it later... That was perhaps just confusing and weird "speedup" and in reality pretty useless... :)

**Pull request merged**
