### PR TITLE
Sort directives alphabetically

### PR DESCRIPTION
**Pull request by lhsazevedo**
Automated with a lazy PHP script

<details>
<summary>Script</summary>

```php
<?php

$source = file_get_contents('input.rst');

$lines = explode("\n", $source);
$output = [];
$start = null;

foreach ($lines as $i => $line) {
    if (preg_match('/^---+$/', $line)) {
        if ($start !== null) {
            $output[] = join("\n", array_slice($lines, $start, $i - $start - 1));
        }

        $start = $i - 1;
    }
}

$output[] = join("\n", array_slice($lines, $start));

sort($output);

file_put_contents('output.rst', join("\n", $output));
```
</details>

### CODE REVIEW

**Comment by lhsazevedo** [comment]
Fixes #369

**Comment by vhelin** [comment]
So few lines of code for such a big change. :) But is .8BIT in the new file, I'm not seeing it in the diff... It could be that I'm not somehow using the diff properly, but just to double check that everything is ok.

**Comment by lhsazevedo** [comment]
Oh, had trouble finding it too haha

It's part of a "unchanged" chunk and GitHub is hiding it. Check line 326/226 (old/new).

**Comment by vhelin** [comment]
Well, considering that, and that this change is +1,822 −1,822 - I assume nothing is lost and you know your PHP (I don't). :)

Thanks!

**Comment by lhsazevedo** [comment]
No problem!

Just triple checking:
1. Download both unsorted ([01cc819d51](https://github.com/vhelin/wla-dx/blob/01cc819d51b82769401e2e902826b9e9d9690127/doc/asmdiv.rst)) and sorted ([2fcc4b490c](https://github.com/vhelin/wla-dx/blob/2fcc4b490ca08c7e23d386c163a8cda0e53d42a9/doc/asmdiv.rst)) files;
2. Split them into words; 
3. Sort the words and hash the resulting serialized array.
```php
<?php

$unsortedUrl = 'https://github.com/vhelin/wla-dx/raw/01cc819d51b82769401e2e902826b9e9d9690127/doc/asmdiv.rst';
$sortedUrl   = 'https://github.com/vhelin/wla-dx/raw/2fcc4b490ca08c7e23d386c163a8cda0e53d42a9/doc/asmdiv.rst';

echo "Fetching files...\n";
$unsorted = file_get_contents($unsortedUrl);
$sorted = file_get_contents($sortedUrl);

echo ("Spliting into words...\n");
$unsortedWords = preg_split('/\s+/', $unsorted);
$sortedWords = preg_split('/\s+/', $sorted);

echo ("Sorting words and calculating hash...\n");
echo sha1(serialize(sort($unsortedWords))) . "\n";
echo sha1(serialize(sort($sortedWords))) . "\n";
```
Outputs:
```
$ php check.php 
Fetching files...
Spliting into words...
Sorting words and calculating hash...
354391e2f51edd6b5ae7c7c321dcc1b6cca6e7c1
354391e2f51edd6b5ae7c7c321dcc1b6cca6e7c1
```

**Comment by vhelin** [comment]
Thanks for the extra effort! :) Gotta love your PHP skills.

**Comment by lhsazevedo** [comment]
Thanks, there's a lot more to learn, maybe it's just a good tool for the job =D

I'm struggling to learn C++ though and it's func<type>() thingy :exploding_head:

**Comment by vhelin** [comment]
I'm nowadays trying to avoid C++ - For me it's just a billion times more complex than C with all the problems of C plus plenty of new problems. :) C#/Java are much more usable OO languages...

And with Unity3D and C# you can transpile C# into C++ when you make builds so you get all the speed benefits of C++, but don't have to touch it at all. :)

**Pull request merged**
