### PR TITLE
Fixes for MSVC compiler

### PR DESCRIPTION
**Pull request by maxim-zhao**
Yet more strlen casts to int...

### CODE REVIEW

**Comment by vhelin** [comment]
Sorry, and thanks!

**Comment by maxim-zhao** [comment]
Could you add an msvc build to your continuous builds? I'm just doing this on my fork (in an MSVC AppVeyor environment):
```
cmake .
cmake --build . --config Release -j
```
I've no experience with the Azure tools for this...

**Comment by vhelin** [comment]
I managed to create a new Azure Pipeline for Windows+MSVC, but couldn't run the test Bash scripts there. I think we need a .bat version of run_tests.sh

**Comment by vhelin** [comment]
Does one build the Debug version like this?

```
cmake .
cmake --build . --config Debug -j
```

**Pull request merged**
