### PR TITLE
wlalink: silent discard sections with -n

### PR DESCRIPTION
**Pull request by nicklausw**
#97. It gets annoying having tons of messages on the command line saying that sections are discarded, so here's an option for the program to keep quiet.

### CODE REVIEW

**Comment by vhelin** [comment]
Good idea, but isn't "-q" usually used to "quiet" things down? :)

**Comment by nicklausw** [comment]
Yeah, but I don't want to completely silence the program, and if I ever did then I'd want -q to be used for that.

**Comment by vhelin** [comment]
How's this usually taken care of?

  -q:d
  -q:discard
  --quiet:discard
  --quiet=discard

??? Using a random letter just to make one option's output to disappear is
not very logical...

**Comment by nicklausw** [comment]
We could have more separate verbose options like -quiet-discard, but this wouldn't work very well with how the program takes input.

**Comment by bazzinotti** [comment]
> Using a random letter just to make one option's output to disappear is
not very logical...

I agree

> How's this usually taken care of?
  -q:d
  -q:discard
  --quiet:discard
  --quiet=discard

Most programs I use in the wild (I'm mostly a OSX / Linux user) will allow a single-letter flag (`-q`) and and expanded version (`--quiet`).

For a flag to accept multiple sub-options, I typically see a comma-dilineated argument. Here's are some examples:

`-q discard,foo`
`--quiet=discard,foo`
`--quiet discard,foo`

> We could have more separate verbose options like -quiet-discard

Comma-separated sub-options can save from the word 'quiet' repeated for every single quiet-option. Since `quiet` sub-options sound like something that could grow, I rest my case.

---

I'm not familiar with WLA-DX's arg parsing impl, but `getopt_long` is a long-proven method to implementing proper argument parsing on *nix. http://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Option-Example.html#Getopt-Long-Option-Example. Their `struct` could be used as an inspiration. I believe there are also `getopt_long` windows ports, but I bet we can simply morph the current parsing code a little bit.

As far as parsing the comma-separated sub-options, there's a neat C function I remember off the top of my head for this: 

```
/* parse single string fields separated by commas */
#include <stdio.h>
#include <string.h>
int main()
{
  char test[] = "discard,foo,bar";
  char sep[] = ",";
  char *word;

  for (word = strtok(test, sep);
       word;
       word = strtok(NULL, sep))
  {
    printf("%s\n", word);
  }
}
```

Anyone experienced in string parsing will probably laugh at the mention of `strtok` because it's implied to understand it long before involving oneself to write something like WLA-DX, am I right? But I realize all kinds of people read here, so I post it succinctly.

**Comment by vhelin** [comment]
On Mon, Apr 18, 2016 at 12:06 AM, Bazz <notifications@github.com> wrote:

> Using a random letter just to make one option's output to disappear is
> not very logical...
>
> I agree
>
> How's this usually taken care of?
> -q:d
> -q:discard
> --quiet:discard
> --quiet=discard
>
> Most programs I use in the wild (I'm mostly a OSX / Linux user) will allow
> a single-letter flag (-q) and and expanded version (--quiet).
>
> For a flag to accept multiple sub-options, I typically see a
> comma-dilineated argument. Here's are some examples:
>
> -q discard,foo
> --quiet=discard,foo
> --quiet discard,foo
>
> We could have more separate verbose options like -quiet-discard
>
> Comma-separated sub-options can save from the word 'quiet' repeated for
> every single quiet-option. Since quiet sub-options sound like something
> that could grow, I rest my case.
>

This sounds good also if it's also the defacto way of doing the silencing,
and yeah, future proof as well.

-q discard,foo
--quiet discard,foo

I'm happy with either one of these (or both). :)



> ------------------------------
>
> I'm not familiar with WLA-DX's arg parsing impl, but getopt_long is a
> long-proven method to implementing proper argument parsing on *nix.
> http://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Option-Example.html#Getopt-Long-Option-Example.
> Their struct could be used as an inspiration. I believe there are also
> getopt_long windows ports, but I bet we can simply morph the current
> parsing code a little bit.
>
> As far as parsing the comma-separated sub-options, there's a neat C
> function I remember off the top of my head for this:
>
> /* parse single string fields separated by commas */
> #include <stdio.h>
> #include <string.h>
> int main()
> {
>   char test[] = "discard,foo,bar";
>   char sep[] = ",";
>   char *word;
>
>   for (word = strtok(test, sep);
>        word;
>        word = strtok(NULL, sep))
>   {
>     printf("%s\n", word);
>   }
> }
>
> Anyone experienced in string parsing will probably laugh at the mention of
> strtok because it's implied to understand it long before involving
> oneself to write something like WLA-DX, am I right? But I realize all kinds
> of people read here, so I post it succinctly.
>

Well, the world is full of functions, can't know them all. :) Anyway, that
looks like a good way of splitting that list into atoms.

**Comment by nicklausw** [comment]
This is outdated, I'll rewrite it later today. How's --quiet-discard sound?

**Comment by cr1901** [comment]
I'd suggest -q, -qq, -qqq, etc personally. Supporting a single long/GNU argument where everything else is a single letter (or arguments chained together) is jarring to me.

**Comment by vhelin** [comment]
Good point!

  -q

We already have that, but could extend it to handle modes?

  ./wla-gb -q -o output.o main.s

... is the old way and should work, plus this new

  ./wla-gb -q the-current-mode-needs-a-name -q discard -q foo -q bar -o
output.o main.s

? Ok? Or the current -q could also be split into sub modes... ?

**Comment by nicklausw** [comment]
I could do that. There'd be two for now, maybe the old one is "output" and then "discard"?

**Comment by vhelin** [comment]
I think I'll look into what the -q does currently first... :)

**Comment by nicklausw** [comment]
Now I know that wlalink had no quiet mode before. I am silly.

So I've added in wlalink's one quiet type, which is discard, and it just looks wrong.

```

WLALINK GB-Z80/Z80/6502/65C02/6510/65816/HUC6280/SPC-700 WLA Macro Assembler Linker v5.8b
Written by Ville Helin in 2000-2008 - In GitHub since 2014: https://github.com/vhelin/wla-dx
USAGE: wlalink [OPTIONS] <LINK FILE> <OUTPUT FILE>

Options:
-b  Program file output
-d  Discard unreferenced sections
-i  Write list files
-r  ROM file output (default)
-s  Write also a NO$GMB symbol file
-S  Write also a WLA symbol file
-v  Verbose messages
-q [QTYP]  Quiet output
    DISCARD  Silent discard unreferenced sections
-L [DIR]  Library directory
```

Is there a better way of describing quiet types properly in the args? This is why I just wanted to add verbose arguments like --quiet-discard.

**Comment by nicklausw** [comment]
...Or since verbose is out of the picture, would just -qd work since there's no other quiet options?

**Pull request closed without merging**
