### PR TITLE
Implemented .COUNTRYCODE

### PR DESCRIPTION
**Pull request by nicklausw**
Handles #47. Surprisingly easy to add in.

### CODE REVIEW

**Comment by vhelin** [comment]
Hmm

+    if (rambanks_defined != 0) {
+      if (rambanks != d) {
+        print_error(".COUNTRYCODE was defined for the second time.\n", ERROR_DIR);
+        return FAILED;
+      }
+      return SUCCEEDED;
+    }

... ? Rambanks and countrycode?

**Comment by vhelin** [comment]
PS. Any sources that'd contain all the country codes? Pan Docs has them not.

**Comment by nicklausw** [comment]
Sorry, I just copied over the cartridgetype code. Will add fix to pull request. Also will try finding all the codes, because I recall there being one...

**Comment by nicklausw** [comment]
Should be good now.

**Comment by vhelin** [comment]
Thanks man, looks good to go! :)

**Comment by vhelin** [comment]
If you could add some more info about the country codes to the README, that'd be great! I made a quick Google, but didn't find anything about them (only that 0x00 + 0x01)...

**Pull request merged**
